name: Python CI

on:
  push:
    branches: ["main"]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Kodni yuklash
        uses: actions/checkout@v4

      - name: Python o‘rnatish
        uses: actions/setup-python@v5
        with:
          python-version: "3.9"

      - name: Kutubxonalar
        run: |
          pip install flake8 pytest

      - name: Kodni tekshirish
        run: |
          flake8 .

      - name: Testlarni ishga tushirish
        run: |
          pytest
